"""
Pydantic Schemas for Question Generation, Ingestion, and Banking.
"""

from typing import List, Optional, Literal, Dict, Any
from pydantic import BaseModel, Field, model_validator


class QuestionOptionSchema(BaseModel):
    """MCQ Option representation."""
    option_key: Literal["A", "B", "C", "D"]
    option_text: str = Field(..., min_length=1)
    is_correct: bool = False


class QuestionCreateSchema(BaseModel):
    """
    Schema for validating candidate questions generated by the AI or submitted manually.
    """
    section_code: Literal["VARC", "DILR", "QA"]
    topic_code: str = Field(..., min_length=2)
    subtopic_code: str = Field(..., min_length=2)
    question_type: Literal["MCQ", "TITA"]
    question_text: str = Field(..., min_length=10)
    options: Optional[List[QuestionOptionSchema]] = None
    correct_answer: str = Field(..., min_length=1)
    explanation: str = Field(..., min_length=15)
    difficulty_level: int = Field(default=3, ge=1, le=5)
    verification_expression: Optional[str] = Field(
        None,
        description="SymPy-evaluable Python mathematical expression for deterministic verification"
    )

    @model_validator(mode="after")
    def validate_mcq_options(self) -> "QuestionCreateSchema":
        """
        Enforces CAT MCQ structural invariants:
        1. MCQs must have exactly 4 options (A, B, C, D).
        2. All 4 options must have distinct text (no duplicate distractors).
        3. Exactly one option must have is_correct == True.
        4. The correct option's key must match correct_answer.
        """
        if self.question_type == "MCQ":
            if not self.options or len(self.options) != 4:
                raise ValueError("MCQ questions must contain exactly 4 options.")

            keys = {opt.option_key for opt in self.options}
            if keys != {"A", "B", "C", "D"}:
                raise ValueError("MCQ options must have keys 'A', 'B', 'C', and 'D'.")

            unique_texts = {opt.option_text.strip().lower() for opt in self.options}
            if len(unique_texts) != 4:
                raise ValueError("All 4 MCQ option texts must be distinct (no duplicate distractors).")

            correct_opts = [opt for opt in self.options if opt.is_correct]
            if len(correct_opts) != 1:
                raise ValueError("Exactly one MCQ option must be marked as is_correct=True.")

            if correct_opts[0].option_key.upper() != self.correct_answer.strip().upper():
                raise ValueError(
                    f"Option marked is_correct ({correct_opts[0].option_key}) does not match correct_answer ({self.correct_answer})."
                )
        elif self.question_type == "TITA":
            if self.options and len(self.options) > 0:
                raise ValueError("TITA questions must not contain options.")

        return self


class QuestionResponseSchema(BaseModel):
    """
    Public question schema returned to students during a live test.
    CRITICAL: Answer keys and explanations are omitted!
    """
    question_id: str
    question_type: str
    question_text: str
    options: Optional[List[Dict[str, str]]] = None  # List of {"key": "A", "text": "..."}
    difficulty_level: int


class QuestionDetailSchema(QuestionResponseSchema):
    """
    Full question schema including verified answer and explanation (used for review/analytics).
    """
    correct_answer: str
    explanation: str
    verification_metadata: Optional[Dict[str, Any]] = None
